version: '3.4'
services:
  master:
    image: redis
    container_name: redis-master
    restart: always
    command: redis-server --port 6379 --requirepass 1234 --masterauth 1234
    ports:
      - 6379:6379
  slave1:
    image: redis
    container_name: redis-slave-1
    restart: always
    command: redis-server --slaveof redis-master 6379 --port 6379 --requirepass 1234 --masterauth 1234
    ports:
      - 6380:6379
  slave2:
    image: redis
    container_name: redis-slave-2
    restart: always
    command: redis-server --slaveof redis-master 6379 --port 6379 --requirepass 1234 --masterauth 1234
    ports:
      - 6381:6379